# Generated by Django 3.2.2 on 2021-05-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwAD', models.CharField(max_length=20)),
                ('tokenAD', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userad',
            name='pwAD',
        ),
    ]
