# Generated by Django 3.2.2 on 2021-06-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAD', '0002_auto_20210521_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameAD', models.CharField(max_length=20)),
                ('totals', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
